global using CalamityMod;
global using CalamityMod.Particles;
global using Microsoft.Xna.Framework;
global using Microsoft.Xna.Framework.Graphics;
global using ReLogic.Content;
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using Terraria;
global using Terraria.Audio;
global using Terraria.DataStructures;
global using Terraria.GameContent;
global using Terraria.ID;
global using Terraria.Localization;
global using Terraria.ModLoader;
global using Terraria.ObjectData;
global using static CalamityMod.CalamityUtils;
global using static Microsoft.Xna.Framework.MathHelper;
global using static Windfall.Common.Utilities.WindfallUtils;